<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <Version>4.6.0</Version>
    <AssemblyVersion>4.6.0.0</AssemblyVersion>
    <FileVersion>4.6.0.0</FileVersion>
    <InformationalVersion>4.6.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
