export const THEME_DESCRIPTIONS: Readonly<Record<string, string>> = {
  Prism: "LibreSpot's balanced theme with adaptive effects, dynamic accents, and four practical color modes.",
  Compact: "Fits more of large libraries on screen with tighter rows, navigation, and playback controls.",
  Accessibility: "Uses larger targets, stronger focus, readable type, and opaque surfaces for clearer navigation.",
  Sleek: "A refined, low-noise layout with a wide collection of dark, light, and characterful color schemes.",
  Dribbblish: "Puts artwork and color up front with rounded surfaces, a compact sidebar, and nineteen schemes.",
  Ziro: "A crisp modern theme with matched dark and light palettes across blue, green, orange, purple, and red.",
  text: "A type-led theme that pares Spotify back to strong typography, clean spacing, and twenty color choices.",
  StarryNight: "Adds an atmospheric star field and vivid palettes for an immersive music-first look.",
  Turntable: "Reframes playback around a record deck for a focused, tactile now-playing experience.",
  Blackout: "Pushes the client toward true black with restrained surfaces that suit OLED displays.",
  Blossom: "A soft dark treatment with gentle contrast and a calm, uncluttered visual rhythm.",
  BurntSienna: "Uses warm earth tones and understated surfaces for a distinct but readable Spotify layout.",
  Default: "Keeps Spotify's familiar structure while adding a polished Ocean color scheme.",
  Dreary: "Pairs moody surfaces with six palettes ranging from monochrome to warm gold and blue-gray.",
  Flow: "Uses rounded forms and expressive color across pink, green, silver, violet, and ocean palettes.",
  Matte: "Favors quiet, low-glare surfaces with ten neutral and pastel color schemes.",
  Nightlight: "Brings a vivid neon accent to dark Spotify surfaces without changing the core layout heavily.",
  Onepunch: "An illustrated theme with dark, light, and legacy modes for a bold character-driven client.",
  SharkBlue: "A deep blue theme with cool accents and strong separation between Spotify's main regions.",
  Catppuccin: "Applies the complete Catppuccin family: Mocha, Macchiato, Frappé, and Latte.",
  Comfy: "A feature-rich theme with roomy surfaces, configurable panels, and three color families.",
  Bloom: "Brings Fluent-inspired materials, soft depth, and seven dark and light palettes to Spotify.",
  Lucid: "Builds translucent surfaces around album artwork with twelve palettes, including Rose Pine and Dracula.",
  Hazy: "A glass-focused theme with blurred artwork, floating surfaces, and dark or light modes.",
};

export const EXTENSION_DESCRIPTIONS: Readonly<Record<string, string>> = {
  "fullAppDisplay.js": "Turns the current track into a full-window now-playing view with prominent artwork and controls.",
  "shuffle+.js": "Adds smarter shuffle actions for playlists and albums, including reshuffle controls.",
  "trashbin.js": "Lets you hide tracks and artists so Spotify can skip music you do not want in rotation.",
  "keyboardShortcut.js": "Adds an optional set of desktop controls for playback and Spotify navigation.",
  "bookmark.js": "Saves a playback position so you can return to long tracks, mixes, or podcasts later.",
  "loopyLoop.js": "Repeats a chosen section of the current track for practice or close listening.",
  "popupLyrics.js": "Opens the current track's lyrics in a separate compact view when lyrics are available.",
  "autoSkipVideo.js": "Moves past video episodes automatically when you prefer audio-first playback.",
  "autoSkipExplicit.js": "Skips tracks Spotify marks as explicit while the extension is enabled.",
  "webnowplaying.js": "Shares now-playing metadata with compatible desktop overlays and streaming tools.",
  "librespot-engine.js": "Powers this Store, live appearance controls, feature overrides, backups, and named health checks.",
  "hidePodcasts.js": "Hides podcast, episode, and audiobook surfaces when you want Spotify focused on music.",
  "beautiful-lyrics.mjs": "Adds synchronized lyrics, dynamic backgrounds, romanization, and adjustable visual effects.",
  "playlist-icons.js": "Adds custom icons and folder artwork to playlists and Your Library.",
  "volumePercentage.js": "Shows the exact volume percentage beside Spotify's volume control.",
  "adblock.js": "Provides a Spicetify fallback when SpotX patching is unavailable for a newer Spotify build.",
};

export const APP_DESCRIPTIONS: Readonly<Record<string, string>> = {
  librespot: "The built-in Store and live customization workspace you are using now.",
  stats: "Explores top tracks, artists, genres, library trends, and optional Last.fm-backed listening history.",
};
