//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreSpot.Desktop.Properties {
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibreSpot.Desktop.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Main window title
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Subtitle in sidebar header
        /// </summary>
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Default activity title before any action
        /// </summary>
        public static string ActivityReady {
            get {
                return ResourceManager.GetString("ActivityReady", resourceCulture);
            }
        }
        /// <summary>
        ///   Default activity status text
        /// </summary>
        public static string ActivityPickPath {
            get {
                return ResourceManager.GetString("ActivityPickPath", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar nav label for recommended/easy install
        /// </summary>
        public static string ModeRecommendedTitle {
            get {
                return ResourceManager.GetString("ModeRecommendedTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Workspace hero subtitle for recommended mode
        /// </summary>
        public static string ModeRecommendedDescription {
            get {
                return ResourceManager.GetString("ModeRecommendedDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar nav label for custom install
        /// </summary>
        public static string ModeCustomTitle {
            get {
                return ResourceManager.GetString("ModeCustomTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Workspace hero subtitle for custom mode
        /// </summary>
        public static string ModeCustomDescription {
            get {
                return ResourceManager.GetString("ModeCustomDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar nav label for maintenance mode
        /// </summary>
        public static string ModeMaintenanceTitle {
            get {
                return ResourceManager.GetString("ModeMaintenanceTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Workspace hero subtitle for maintenance mode
        /// </summary>
        public static string ModeMaintenanceDescription {
            get {
                return ResourceManager.GetString("ModeMaintenanceDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Hero eyebrow text for recommended/custom modes
        /// </summary>
        public static string HeroGuidedSetup {
            get {
                return ResourceManager.GetString("HeroGuidedSetup", resourceCulture);
            }
        }
        /// <summary>
        ///   Hero eyebrow text for maintenance mode
        /// </summary>
        public static string HeroMaintenanceEyebrow {
            get {
                return ResourceManager.GetString("HeroMaintenanceEyebrow", resourceCulture);
            }
        }
        /// <summary>
        ///   Status when admin privileges are available
        /// </summary>
        public static string ReadyToRun {
            get {
                return ResourceManager.GetString("ReadyToRun", resourceCulture);
            }
        }
        /// <summary>
        ///   Status when admin elevation is required
        /// </summary>
        public static string AdminStepNeeded {
            get {
                return ResourceManager.GetString("AdminStepNeeded", resourceCulture);
            }
        }
        /// <summary>
        ///   Explanation when running as admin
        /// </summary>
        public static string ReadyToRunDescription {
            get {
                return ResourceManager.GetString("ReadyToRunDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Explanation when not running as admin
        /// </summary>
        public static string AdminStepDescription {
            get {
                return ResourceManager.GetString("AdminStepDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Search box watermark text
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        /// <summary>
        ///   Shown when search finds nothing
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        /// <summary>
        ///   Hint below search no-results message
        /// </summary>
        public static string SearchNoResultsHint {
            get {
                return ResourceManager.GetString("SearchNoResultsHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text for search box
        /// </summary>
        public static string SearchHelpText {
            get {
                return ResourceManager.GetString("SearchHelpText", resourceCulture);
            }
        }
        /// <summary>
        ///   Health check passed
        /// </summary>
        public static string SeverityReady {
            get {
                return ResourceManager.GetString("SeverityReady", resourceCulture);
            }
        }
        /// <summary>
        ///   Health check has a non-critical issue
        /// </summary>
        public static string SeverityWarning {
            get {
                return ResourceManager.GetString("SeverityWarning", resourceCulture);
            }
        }
        /// <summary>
        ///   Health check found a serious problem
        /// </summary>
        public static string SeverityCritical {
            get {
                return ResourceManager.GetString("SeverityCritical", resourceCulture);
            }
        }
        /// <summary>
        ///   Informational health detail
        /// </summary>
        public static string SeverityInfo {
            get {
                return ResourceManager.GetString("SeverityInfo", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionCheckMatrix {
            get {
                return ResourceManager.GetString("ActionCheckMatrix", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionCreateBackup {
            get {
                return ResourceManager.GetString("ActionCreateBackup", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionRestoreBackup {
            get {
                return ResourceManager.GetString("ActionRestoreBackup", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionReapply {
            get {
                return ResourceManager.GetString("ActionReapply", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionRepairMarketplace {
            get {
                return ResourceManager.GetString("ActionRepairMarketplace", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionOpenMarketplace {
            get {
                return ResourceManager.GetString("ActionOpenMarketplace", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionSafeMode {
            get {
                return ResourceManager.GetString("ActionSafeMode", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionRestoreVanilla {
            get {
                return ResourceManager.GetString("ActionRestoreVanilla", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title
        /// </summary>
        public static string ActionUninstallSpicetify {
            get {
                return ResourceManager.GetString("ActionUninstallSpicetify", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title — destructive
        /// </summary>
        public static string ActionFullReset {
            get {
                return ResourceManager.GetString("ActionFullReset", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title — destructive
        /// </summary>
        public static string ActionRemoveSelfData {
            get {
                return ResourceManager.GetString("ActionRemoveSelfData", resourceCulture);
            }
        }
        /// <summary>
        ///   Primary install button label
        /// </summary>
        public static string ButtonRunSetup {
            get {
                return ResourceManager.GetString("ButtonRunSetup", resourceCulture);
            }
        }
        /// <summary>
        ///   Cancel/abort button label
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        /// <summary>
        ///   Confirmation dialog continue button
        /// </summary>
        public static string ButtonContinue {
            get {
                return ResourceManager.GetString("ButtonContinue", resourceCulture);
            }
        }
        /// <summary>
        ///   Dismiss/close button
        /// </summary>
        public static string ButtonDismiss {
            get {
                return ResourceManager.GetString("ButtonDismiss", resourceCulture);
            }
        }
        /// <summary>
        ///   Copy log to clipboard button
        /// </summary>
        public static string ButtonCopyLog {
            get {
                return ResourceManager.GetString("ButtonCopyLog", resourceCulture);
            }
        }
        /// <summary>
        ///   Open folder in Explorer button
        /// </summary>
        public static string ButtonOpenFolder {
            get {
                return ResourceManager.GetString("ButtonOpenFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Clear search button
        /// </summary>
        public static string ButtonClearSearch {
            get {
                return ResourceManager.GetString("ButtonClearSearch", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for clear search button
        /// </summary>
        public static string ButtonClearSearchName {
            get {
                return ResourceManager.GetString("ButtonClearSearchName", resourceCulture);
            }
        }
        /// <summary>
        ///   Primary button on recommended mode
        /// </summary>
        public static string ButtonRunRecommendedSetup {
            get {
                return ResourceManager.GetString("ButtonRunRecommendedSetup", resourceCulture);
            }
        }
        /// <summary>
        ///   Primary button on custom mode
        /// </summary>
        public static string ButtonApplyCustomProfile {
            get {
                return ResourceManager.GetString("ButtonApplyCustomProfile", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text for apply button
        /// </summary>
        public static string ButtonApplyCustomProfileHint {
            get {
                return ResourceManager.GetString("ButtonApplyCustomProfileHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Open config folder button
        /// </summary>
        public static string ButtonOpenLibreSpotFolder {
            get {
                return ResourceManager.GetString("ButtonOpenLibreSpotFolder", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar open-folder hint
        /// </summary>
        public static string ButtonOpenLibreSpotFolderHint {
            get {
                return ResourceManager.GetString("ButtonOpenLibreSpotFolderHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Activity panel open-folder hint
        /// </summary>
        public static string ButtonOpenLibreSpotFolderActivityHint {
            get {
                return ResourceManager.GetString("ButtonOpenLibreSpotFolderActivityHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Refresh button label
        /// </summary>
        public static string ButtonRefreshEnvironment {
            get {
                return ResourceManager.GetString("ButtonRefreshEnvironment", resourceCulture);
            }
        }
        /// <summary>
        ///   Refresh button tooltip
        /// </summary>
        public static string ButtonRefreshEnvironmentHint {
            get {
                return ResourceManager.GetString("ButtonRefreshEnvironmentHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Export support bundle button
        /// </summary>
        public static string ButtonExportBundle {
            get {
                return ResourceManager.GetString("ButtonExportBundle", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for export bundle button
        /// </summary>
        public static string ButtonExportBundleName {
            get {
                return ResourceManager.GetString("ButtonExportBundleName", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text for export bundle button
        /// </summary>
        public static string ButtonExportBundleHint {
            get {
                return ResourceManager.GetString("ButtonExportBundleHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Enable auto-reapply button
        /// </summary>
        public static string ButtonEnableWatcher {
            get {
                return ResourceManager.GetString("ButtonEnableWatcher", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name
        /// </summary>
        public static string ButtonEnableWatcherName {
            get {
                return ResourceManager.GetString("ButtonEnableWatcherName", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text
        /// </summary>
        public static string ButtonEnableWatcherHint {
            get {
                return ResourceManager.GetString("ButtonEnableWatcherHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Disable auto-reapply button
        /// </summary>
        public static string ButtonDisableWatcher {
            get {
                return ResourceManager.GetString("ButtonDisableWatcher", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name
        /// </summary>
        public static string ButtonDisableWatcherName {
            get {
                return ResourceManager.GetString("ButtonDisableWatcherName", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text
        /// </summary>
        public static string ButtonDisableWatcherHint {
            get {
                return ResourceManager.GetString("ButtonDisableWatcherHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Cancel active run button
        /// </summary>
        public static string ButtonCancelRun {
            get {
                return ResourceManager.GetString("ButtonCancelRun", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name
        /// </summary>
        public static string ButtonCancelRunName {
            get {
                return ResourceManager.GetString("ButtonCancelRunName", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text
        /// </summary>
        public static string ButtonCancelRunHint {
            get {
                return ResourceManager.GetString("ButtonCancelRunHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Close overlay button
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for copy log button
        /// </summary>
        public static string ButtonCopyLogName {
            get {
                return ResourceManager.GetString("ButtonCopyLogName", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text
        /// </summary>
        public static string ButtonCopyLogHint {
            get {
                return ResourceManager.GetString("ButtonCopyLogHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Initial progress state
        /// </summary>
        public static string ProgressPreparing {
            get {
                return ResourceManager.GetString("ProgressPreparing", resourceCulture);
            }
        }
        /// <summary>
        ///   Final progress state
        /// </summary>
        public static string ProgressComplete {
            get {
                return ResourceManager.GetString("ProgressComplete", resourceCulture);
            }
        }
        /// <summary>
        ///   Final progress substatus
        /// </summary>
        public static string ProgressSpotifyReady {
            get {
                return ResourceManager.GetString("ProgressSpotifyReady", resourceCulture);
            }
        }
        /// <summary>
        ///   Clean install option title
        /// </summary>
        public static string OptionCleanInstall {
            get {
                return ResourceManager.GetString("OptionCleanInstall", resourceCulture);
            }
        }
        /// <summary>
        ///   Clean install option description
        /// </summary>
        public static string OptionCleanInstallDescription {
            get {
                return ResourceManager.GetString("OptionCleanInstallDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Post-install launch option title
        /// </summary>
        public static string OptionLaunchAfter {
            get {
                return ResourceManager.GetString("OptionLaunchAfter", resourceCulture);
            }
        }
        /// <summary>
        ///   Shown after config is saved
        /// </summary>
        public static string ConfigSaved {
            get {
                return ResourceManager.GetString("ConfigSaved", resourceCulture);
            }
        }
        /// <summary>
        ///   Shown when config has unsaved changes
        /// </summary>
        public static string ConfigUnsaved {
            get {
                return ResourceManager.GetString("ConfigUnsaved", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar mode description paragraph
        /// </summary>
        public static string SidebarDescription {
            get {
                return ResourceManager.GetString("SidebarDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar environment section heading
        /// </summary>
        public static string EnvironmentLabel {
            get {
                return ResourceManager.GetString("EnvironmentLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard card label
        /// </summary>
        public static string DashboardSpotifyVersionLabel {
            get {
                return ResourceManager.GetString("DashboardSpotifyVersionLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard card label
        /// </summary>
        public static string DashboardSpicetifyVersionLabel {
            get {
                return ResourceManager.GetString("DashboardSpicetifyVersionLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard card label
        /// </summary>
        public static string DashboardSpotXStateLabel {
            get {
                return ResourceManager.GetString("DashboardSpotXStateLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard card label
        /// </summary>
        public static string DashboardLastPatchLabel {
            get {
                return ResourceManager.GetString("DashboardLastPatchLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard card label
        /// </summary>
        public static string DashboardWatcherLabel {
            get {
                return ResourceManager.GetString("DashboardWatcherLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard fallback value
        /// </summary>
        public static string DashboardUnknownValue {
            get {
                return ResourceManager.GetString("DashboardUnknownValue", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard fallback detail
        /// </summary>
        public static string DashboardSnapshotMissingDetail {
            get {
                return ResourceManager.GetString("DashboardSnapshotMissingDetail", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard last patch fallback value
        /// </summary>
        public static string DashboardNoPatchRecord {
            get {
                return ResourceManager.GetString("DashboardNoPatchRecord", resourceCulture);
            }
        }
        /// <summary>
        ///   Status dashboard last patch fallback detail
        /// </summary>
        public static string DashboardNoPatchRecordDetail {
            get {
                return ResourceManager.GetString("DashboardNoPatchRecordDetail", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar warning count label
        /// </summary>
        public static string SeverityWarningsLabel {
            get {
                return ResourceManager.GetString("SeverityWarningsLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar next-step section heading
        /// </summary>
        public static string NextStepLabel {
            get {
                return ResourceManager.GetString("NextStepLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar profile recovery section heading
        /// </summary>
        public static string ProfileRecoveryLabel {
            get {
                return ResourceManager.GetString("ProfileRecoveryLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Sidebar stack snapshot heading
        /// </summary>
        public static string StackSnapshotLabel {
            get {
                return ResourceManager.GetString("StackSnapshotLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Stack snapshot helper text
        /// </summary>
        public static string StackSnapshotHint {
            get {
                return ResourceManager.GetString("StackSnapshotHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Option card status badge
        /// </summary>
        public static string OptionStatusOptional {
            get {
                return ResourceManager.GetString("OptionStatusOptional", resourceCulture);
            }
        }
        /// <summary>
        ///   Option card status badge
        /// </summary>
        public static string OptionStatusRecommended {
            get {
                return ResourceManager.GetString("OptionStatusRecommended", resourceCulture);
            }
        }
        /// <summary>
        ///   Option card status badge
        /// </summary>
        public static string OptionStatusAdded {
            get {
                return ResourceManager.GetString("OptionStatusAdded", resourceCulture);
            }
        }
        /// <summary>
        ///   Option card status badge
        /// </summary>
        public static string OptionStatusRemoved {
            get {
                return ResourceManager.GetString("OptionStatusRemoved", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension card status badge
        /// </summary>
        public static string ExtensionStatusAvailable {
            get {
                return ResourceManager.GetString("ExtensionStatusAvailable", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension card status badge
        /// </summary>
        public static string ExtensionStatusDefault {
            get {
                return ResourceManager.GetString("ExtensionStatusDefault", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension card status badge
        /// </summary>
        public static string ExtensionStatusAdded {
            get {
                return ResourceManager.GetString("ExtensionStatusAdded", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension card status badge
        /// </summary>
        public static string ExtensionStatusRemoved {
            get {
                return ResourceManager.GetString("ExtensionStatusRemoved", resourceCulture);
            }
        }
        /// <summary>
        ///   Default maintenance card detail text
        /// </summary>
        public static string MaintenanceCardDefaultDetail {
            get {
                return ResourceManager.GetString("MaintenanceCardDefaultDetail", resourceCulture);
            }
        }
        /// <summary>
        ///   Destructive maintenance card detail text
        /// </summary>
        public static string MaintenanceCardDestructiveDetail {
            get {
                return ResourceManager.GetString("MaintenanceCardDestructiveDetail", resourceCulture);
            }
        }
        /// <summary>
        ///   Recommended mode inclusion list heading
        /// </summary>
        public static string WhatIncludesLabel {
            get {
                return ResourceManager.GetString("WhatIncludesLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Recommended mode usage hint
        /// </summary>
        public static string RecommendedModeHint {
            get {
                return ResourceManager.GetString("RecommendedModeHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section heading
        /// </summary>
        public static string InstallPostureSection {
            get {
                return ResourceManager.GetString("InstallPostureSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section description
        /// </summary>
        public static string InstallPostureDescription {
            get {
                return ResourceManager.GetString("InstallPostureDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section heading
        /// </summary>
        public static string AppearanceSection {
            get {
                return ResourceManager.GetString("AppearanceSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section description
        /// </summary>
        public static string AppearanceDescription {
            get {
                return ResourceManager.GetString("AppearanceDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Theme selector label
        /// </summary>
        public static string ThemePackLabel {
            get {
                return ResourceManager.GetString("ThemePackLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Theme selector accessibility hint
        /// </summary>
        public static string ThemePackHint {
            get {
                return ResourceManager.GetString("ThemePackHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Scheme selector label
        /// </summary>
        public static string ColorSchemeLabel {
            get {
                return ResourceManager.GetString("ColorSchemeLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Lyrics theme selector label
        /// </summary>
        public static string LyricsThemeLabel {
            get {
                return ResourceManager.GetString("LyricsThemeLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Cache limit field label
        /// </summary>
        public static string CacheLimitLabel {
            get {
                return ResourceManager.GetString("CacheLimitLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for cache field
        /// </summary>
        public static string CacheLimitName {
            get {
                return ResourceManager.GetString("CacheLimitName", resourceCulture);
            }
        }
        /// <summary>
        ///   Cache limit accessibility hint
        /// </summary>
        public static string CacheLimitHint {
            get {
                return ResourceManager.GetString("CacheLimitHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Cache limit unit suffix
        /// </summary>
        public static string CacheLimitUnit {
            get {
                return ResourceManager.GetString("CacheLimitUnit", resourceCulture);
            }
        }
        /// <summary>
        ///   Cache limit helper text
        /// </summary>
        public static string CacheLimitDefault {
            get {
                return ResourceManager.GetString("CacheLimitDefault", resourceCulture);
            }
        }
        /// <summary>
        ///   Section label for Spotify version targeting
        /// </summary>
        public static string CompatibilityTargetLabel {
            get {
                return ResourceManager.GetString("CompatibilityTargetLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Version dropdown label
        /// </summary>
        public static string SpotifyBuildLabel {
            get {
                return ResourceManager.GetString("SpotifyBuildLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for version dropdown
        /// </summary>
        public static string SpotifyCompatibilityName {
            get {
                return ResourceManager.GetString("SpotifyCompatibilityName", resourceCulture);
            }
        }
        /// <summary>
        ///   Version dropdown accessibility hint
        /// </summary>
        public static string SpotifyCompatibilityHint {
            get {
                return ResourceManager.GetString("SpotifyCompatibilityHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Download method section label
        /// </summary>
        public static string DownloadPathLabel {
            get {
                return ResourceManager.GetString("DownloadPathLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for download method dropdown
        /// </summary>
        public static string DownloadMethodName {
            get {
                return ResourceManager.GetString("DownloadMethodName", resourceCulture);
            }
        }
        /// <summary>
        ///   Download method accessibility hint
        /// </summary>
        public static string DownloadMethodHint {
            get {
                return ResourceManager.GetString("DownloadMethodHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section heading
        /// </summary>
        public static string PlaybackBehaviorSection {
            get {
                return ResourceManager.GetString("PlaybackBehaviorSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section description
        /// </summary>
        public static string PlaybackBehaviorDescription {
            get {
                return ResourceManager.GetString("PlaybackBehaviorDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Option group label
        /// </summary>
        public static string CoreBehaviorLabel {
            get {
                return ResourceManager.GetString("CoreBehaviorLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Option group label
        /// </summary>
        public static string InterfaceTuningLabel {
            get {
                return ResourceManager.GetString("InterfaceTuningLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section heading
        /// </summary>
        public static string AdvancedAdjustmentsSection {
            get {
                return ResourceManager.GetString("AdvancedAdjustmentsSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Advanced section warning
        /// </summary>
        public static string AdvancedAdjustmentsHint {
            get {
                return ResourceManager.GetString("AdvancedAdjustmentsHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Option group label
        /// </summary>
        public static string ExperienceExtrasLabel {
            get {
                return ResourceManager.GetString("ExperienceExtrasLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section heading
        /// </summary>
        public static string BuiltInExtensionsSection {
            get {
                return ResourceManager.GetString("BuiltInExtensionsSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Custom mode section description
        /// </summary>
        public static string BuiltInExtensionsDescription {
            get {
                return ResourceManager.GetString("BuiltInExtensionsDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary sidebar heading
        /// </summary>
        public static string ProfileSummaryLabel {
            get {
                return ResourceManager.GetString("ProfileSummaryLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string InstallPostureLabel {
            get {
                return ResourceManager.GetString("InstallPostureLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string ProfileChangesLabel {
            get {
                return ResourceManager.GetString("ProfileChangesLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string ExtensionsLabel {
            get {
                return ResourceManager.GetString("ExtensionsLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string AccessLabel {
            get {
                return ResourceManager.GetString("AccessLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string RunReadinessLabel {
            get {
                return ResourceManager.GetString("RunReadinessLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string CurrentSelectionsLabel {
            get {
                return ResourceManager.GetString("CurrentSelectionsLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string DownloadRouteLabel {
            get {
                return ResourceManager.GetString("DownloadRouteLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Summary section label
        /// </summary>
        public static string WhatToWatchLabel {
            get {
                return ResourceManager.GetString("WhatToWatchLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Empty state for extensions list
        /// </summary>
        public static string NoExtensionsSelected {
            get {
                return ResourceManager.GetString("NoExtensionsSelected", resourceCulture);
            }
        }
        /// <summary>
        ///   Empty state hint for extensions
        /// </summary>
        public static string NoExtensionsHint {
            get {
                return ResourceManager.GetString("NoExtensionsHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance status section label
        /// </summary>
        public static string StackLabel {
            get {
                return ResourceManager.GetString("StackLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance status section label
        /// </summary>
        public static string BackupsLabel {
            get {
                return ResourceManager.GetString("BackupsLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance status section label
        /// </summary>
        public static string MarketplaceLabel {
            get {
                return ResourceManager.GetString("MarketplaceLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance status section label
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Support bundle section heading
        /// </summary>
        public static string SupportBundleTitle {
            get {
                return ResourceManager.GetString("SupportBundleTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Watcher section heading
        /// </summary>
        public static string AutoReapplyTitle {
            get {
                return ResourceManager.GetString("AutoReapplyTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action group heading
        /// </summary>
        public static string RefreshRecoverSection {
            get {
                return ResourceManager.GetString("RefreshRecoverSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action group description
        /// </summary>
        public static string RefreshRecoverDescription {
            get {
                return ResourceManager.GetString("RefreshRecoverDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance destructive action group heading
        /// </summary>
        public static string ResetSection {
            get {
                return ResourceManager.GetString("ResetSection", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance destructive group description
        /// </summary>
        public static string ResetDescription {
            get {
                return ResourceManager.GetString("ResetDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance footer hint
        /// </summary>
        public static string MaintenanceClosingHint {
            get {
                return ResourceManager.GetString("MaintenanceClosingHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for activity overlay
        /// </summary>
        public static string ActivityDialogName {
            get {
                return ResourceManager.GetString("ActivityDialogName", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility help text for activity overlay
        /// </summary>
        public static string ActivityDialogHint {
            get {
                return ResourceManager.GetString("ActivityDialogHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Elapsed time label
        /// </summary>
        public static string ElapsedLabel {
            get {
                return ResourceManager.GetString("ElapsedLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Accessibility name for progress bar
        /// </summary>
        public static string ProgressBarName {
            get {
                return ResourceManager.GetString("ProgressBarName", resourceCulture);
            }
        }
        /// <summary>
        ///   Undo pane heading after a successful run
        /// </summary>
        public static string UndoPaneTitle {
            get {
                return ResourceManager.GetString("UndoPaneTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Undo pane description after a successful run
        /// </summary>
        public static string UndoPaneDescription {
            get {
                return ResourceManager.GetString("UndoPaneDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Undo pane rollback hint label
        /// </summary>
        public static string UndoPaneUndoLabel {
            get {
                return ResourceManager.GetString("UndoPaneUndoLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Log section heading
        /// </summary>
        public static string RunLogLabel {
            get {
                return ResourceManager.GetString("RunLogLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Log section description
        /// </summary>
        public static string RunLogDescription {
            get {
                return ResourceManager.GetString("RunLogDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Log empty state heading
        /// </summary>
        public static string LogEmptyStateTitle {
            get {
                return ResourceManager.GetString("LogEmptyStateTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Log empty state description
        /// </summary>
        public static string LogEmptyStateHint {
            get {
                return ResourceManager.GetString("LogEmptyStateHint", resourceCulture);
            }
        }
        /// <summary>
        ///   Default prompt overlay title
        /// </summary>
        public static string PromptActionConfirm {
            get {
                return ResourceManager.GetString("PromptActionConfirm", resourceCulture);
            }
        }
        /// <summary>
        ///   Prompt overlay title for destructive actions
        /// </summary>
        public static string PromptActionReset {
            get {
                return ResourceManager.GetString("PromptActionReset", resourceCulture);
            }
        }
        /// <summary>
        ///   Default file count display
        /// </summary>
        public static string FilesNone {
            get {
                return ResourceManager.GetString("FilesNone", resourceCulture);
            }
        }
        /// <summary>
        ///   Default size display
        /// </summary>
        public static string SizeNone {
            get {
                return ResourceManager.GetString("SizeNone", resourceCulture);
            }
        }
        /// <summary>
        ///   Support bundle empty state
        /// </summary>
        public static string NoBundleExported {
            get {
                return ResourceManager.GetString("NoBundleExported", resourceCulture);
            }
        }
        /// <summary>
        ///   Export bundle dialog title
        /// </summary>
        public static string ExportBundleTitle {
            get {
                return ResourceManager.GetString("ExportBundleTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Status while backend is starting
        /// </summary>
        public static string PreparingBackend {
            get {
                return ResourceManager.GetString("PreparingBackend", resourceCulture);
            }
        }
        /// <summary>
        ///   Run was canceled
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        /// <summary>
        ///   Config save was canceled
        /// </summary>
        public static string ConfigSaveCanceled {
            get {
                return ResourceManager.GetString("ConfigSaveCanceled", resourceCulture);
            }
        }
        /// <summary>
        ///   Activity title when run has warnings
        /// </summary>
        public static string RunNeedsAttention {
            get {
                return ResourceManager.GetString("RunNeedsAttention", resourceCulture);
            }
        }
        /// <summary>
        ///   Activity title when run finishes successfully
        /// </summary>
        public static string RunComplete {
            get {
                return ResourceManager.GetString("RunComplete", resourceCulture);
            }
        }
        /// <summary>
        ///   Status while backend is stopping
        /// </summary>
        public static string StoppingBackend {
            get {
                return ResourceManager.GetString("StoppingBackend", resourceCulture);
            }
        }
        /// <summary>
        ///   Run status badge
        /// </summary>
        public static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        /// <summary>
        ///   Run status badge when warnings exist
        /// </summary>
        public static string StatusNeedsReview {
            get {
                return ResourceManager.GetString("StatusNeedsReview", resourceCulture);
            }
        }
        /// <summary>
        ///   Run status badge on success
        /// </summary>
        public static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        /// <summary>
        ///   Progress step label
        /// </summary>
        public static string CurrentStep {
            get {
                return ResourceManager.GetString("CurrentStep", resourceCulture);
            }
        }
        /// <summary>
        ///   Status label
        /// </summary>
        public static string RunStatus {
            get {
                return ResourceManager.GetString("RunStatus", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for CleanInstall
        /// </summary>
        public static string Option_CleanInstall_Title {
            get {
                return ResourceManager.GetString("Option_CleanInstall_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for CleanInstall
        /// </summary>
        public static string Option_CleanInstall_Description {
            get {
                return ResourceManager.GetString("Option_CleanInstall_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for LaunchAfter
        /// </summary>
        public static string Option_LaunchAfter_Title {
            get {
                return ResourceManager.GetString("Option_LaunchAfter_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for LaunchAfter
        /// </summary>
        public static string Option_LaunchAfter_Description {
            get {
                return ResourceManager.GetString("Option_LaunchAfter_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_NewTheme
        /// </summary>
        public static string Option_SpotX_NewTheme_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_NewTheme_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_NewTheme
        /// </summary>
        public static string Option_SpotX_NewTheme_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_NewTheme_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_PodcastsOff
        /// </summary>
        public static string Option_SpotX_PodcastsOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_PodcastsOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_PodcastsOff
        /// </summary>
        public static string Option_SpotX_PodcastsOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_PodcastsOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_BlockUpdate
        /// </summary>
        public static string Option_SpotX_BlockUpdate_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_BlockUpdate_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_BlockUpdate
        /// </summary>
        public static string Option_SpotX_BlockUpdate_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_BlockUpdate_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_AdSectionsOff
        /// </summary>
        public static string Option_SpotX_AdSectionsOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_AdSectionsOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_AdSectionsOff
        /// </summary>
        public static string Option_SpotX_AdSectionsOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_AdSectionsOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_Premium
        /// </summary>
        public static string Option_SpotX_Premium_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_Premium_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_Premium
        /// </summary>
        public static string Option_SpotX_Premium_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_Premium_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_DisableStartup
        /// </summary>
        public static string Option_SpotX_DisableStartup_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_DisableStartup_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_DisableStartup
        /// </summary>
        public static string Option_SpotX_DisableStartup_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_DisableStartup_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_NoShortcut
        /// </summary>
        public static string Option_SpotX_NoShortcut_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_NoShortcut_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_NoShortcut
        /// </summary>
        public static string Option_SpotX_NoShortcut_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_NoShortcut_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_StartSpoti
        /// </summary>
        public static string Option_SpotX_StartSpoti_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_StartSpoti_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_StartSpoti
        /// </summary>
        public static string Option_SpotX_StartSpoti_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_StartSpoti_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_LyricsEnabled
        /// </summary>
        public static string Option_SpotX_LyricsEnabled_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_LyricsEnabled_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_LyricsEnabled
        /// </summary>
        public static string Option_SpotX_LyricsEnabled_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_LyricsEnabled_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_TopSearch
        /// </summary>
        public static string Option_SpotX_TopSearch_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_TopSearch_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_TopSearch
        /// </summary>
        public static string Option_SpotX_TopSearch_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_TopSearch_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_RightSidebarOff
        /// </summary>
        public static string Option_SpotX_RightSidebarOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_RightSidebarOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_RightSidebarOff
        /// </summary>
        public static string Option_SpotX_RightSidebarOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_RightSidebarOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_RightSidebarClr
        /// </summary>
        public static string Option_SpotX_RightSidebarClr_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_RightSidebarClr_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_RightSidebarClr
        /// </summary>
        public static string Option_SpotX_RightSidebarClr_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_RightSidebarClr_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_CanvasHomeOff
        /// </summary>
        public static string Option_SpotX_CanvasHomeOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_CanvasHomeOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_CanvasHomeOff
        /// </summary>
        public static string Option_SpotX_CanvasHomeOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_CanvasHomeOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_HomeSubOff
        /// </summary>
        public static string Option_SpotX_HomeSubOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_HomeSubOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_HomeSubOff
        /// </summary>
        public static string Option_SpotX_HomeSubOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_HomeSubOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_OldLyrics
        /// </summary>
        public static string Option_SpotX_OldLyrics_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_OldLyrics_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_OldLyrics
        /// </summary>
        public static string Option_SpotX_OldLyrics_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_OldLyrics_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_HideColIconOff
        /// </summary>
        public static string Option_SpotX_HideColIconOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_HideColIconOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_HideColIconOff
        /// </summary>
        public static string Option_SpotX_HideColIconOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_HideColIconOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_Plus
        /// </summary>
        public static string Option_SpotX_Plus_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_Plus_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_Plus
        /// </summary>
        public static string Option_SpotX_Plus_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_Plus_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_NewFullscreen
        /// </summary>
        public static string Option_SpotX_NewFullscreen_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_NewFullscreen_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_NewFullscreen
        /// </summary>
        public static string Option_SpotX_NewFullscreen_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_NewFullscreen_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_FunnyProgress
        /// </summary>
        public static string Option_SpotX_FunnyProgress_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_FunnyProgress_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_FunnyProgress
        /// </summary>
        public static string Option_SpotX_FunnyProgress_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_FunnyProgress_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_ExpSpotify
        /// </summary>
        public static string Option_SpotX_ExpSpotify_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_ExpSpotify_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_ExpSpotify
        /// </summary>
        public static string Option_SpotX_ExpSpotify_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_ExpSpotify_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_LyricsBlock
        /// </summary>
        public static string Option_SpotX_LyricsBlock_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_LyricsBlock_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_LyricsBlock
        /// </summary>
        public static string Option_SpotX_LyricsBlock_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_LyricsBlock_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_SendVersionOff
        /// </summary>
        public static string Option_SpotX_SendVersionOff_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_SendVersionOff_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_SendVersionOff
        /// </summary>
        public static string Option_SpotX_SendVersionOff_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_SendVersionOff_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_DevTools
        /// </summary>
        public static string Option_SpotX_DevTools_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_DevTools_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_DevTools
        /// </summary>
        public static string Option_SpotX_DevTools_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_DevTools_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_Mirror
        /// </summary>
        public static string Option_SpotX_Mirror_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_Mirror_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_Mirror
        /// </summary>
        public static string Option_SpotX_Mirror_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_Mirror_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for SpotX_ConfirmUninstall
        /// </summary>
        public static string Option_SpotX_ConfirmUninstall_Title {
            get {
                return ResourceManager.GetString("Option_SpotX_ConfirmUninstall_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for SpotX_ConfirmUninstall
        /// </summary>
        public static string Option_SpotX_ConfirmUninstall_Description {
            get {
                return ResourceManager.GetString("Option_SpotX_ConfirmUninstall_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Option title for Spicetify_Marketplace
        /// </summary>
        public static string Option_Spicetify_Marketplace_Title {
            get {
                return ResourceManager.GetString("Option_Spicetify_Marketplace_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Option description for Spicetify_Marketplace
        /// </summary>
        public static string Option_Spicetify_Marketplace_Description {
            get {
                return ResourceManager.GetString("Option_Spicetify_Marketplace_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for fullAppDisplay.js
        /// </summary>
        public static string Extension_fullAppDisplay_Title {
            get {
                return ResourceManager.GetString("Extension_fullAppDisplay_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for fullAppDisplay.js
        /// </summary>
        public static string Extension_fullAppDisplay_Description {
            get {
                return ResourceManager.GetString("Extension_fullAppDisplay_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for shuffle+.js
        /// </summary>
        public static string Extension_shuffle_plus_Title {
            get {
                return ResourceManager.GetString("Extension_shuffle_plus_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for shuffle+.js
        /// </summary>
        public static string Extension_shuffle_plus_Description {
            get {
                return ResourceManager.GetString("Extension_shuffle_plus_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for trashbin.js
        /// </summary>
        public static string Extension_trashbin_Title {
            get {
                return ResourceManager.GetString("Extension_trashbin_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for trashbin.js
        /// </summary>
        public static string Extension_trashbin_Description {
            get {
                return ResourceManager.GetString("Extension_trashbin_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for keyboardShortcut.js
        /// </summary>
        public static string Extension_keyboardShortcut_Title {
            get {
                return ResourceManager.GetString("Extension_keyboardShortcut_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for keyboardShortcut.js
        /// </summary>
        public static string Extension_keyboardShortcut_Description {
            get {
                return ResourceManager.GetString("Extension_keyboardShortcut_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for bookmark.js
        /// </summary>
        public static string Extension_bookmark_Title {
            get {
                return ResourceManager.GetString("Extension_bookmark_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for bookmark.js
        /// </summary>
        public static string Extension_bookmark_Description {
            get {
                return ResourceManager.GetString("Extension_bookmark_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for loopyLoop.js
        /// </summary>
        public static string Extension_loopyLoop_Title {
            get {
                return ResourceManager.GetString("Extension_loopyLoop_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for loopyLoop.js
        /// </summary>
        public static string Extension_loopyLoop_Description {
            get {
                return ResourceManager.GetString("Extension_loopyLoop_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for popupLyrics.js
        /// </summary>
        public static string Extension_popupLyrics_Title {
            get {
                return ResourceManager.GetString("Extension_popupLyrics_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for popupLyrics.js
        /// </summary>
        public static string Extension_popupLyrics_Description {
            get {
                return ResourceManager.GetString("Extension_popupLyrics_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for autoSkipVideo.js
        /// </summary>
        public static string Extension_autoSkipVideo_Title {
            get {
                return ResourceManager.GetString("Extension_autoSkipVideo_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for autoSkipVideo.js
        /// </summary>
        public static string Extension_autoSkipVideo_Description {
            get {
                return ResourceManager.GetString("Extension_autoSkipVideo_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for autoSkipExplicit.js
        /// </summary>
        public static string Extension_autoSkipExplicit_Title {
            get {
                return ResourceManager.GetString("Extension_autoSkipExplicit_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for autoSkipExplicit.js
        /// </summary>
        public static string Extension_autoSkipExplicit_Description {
            get {
                return ResourceManager.GetString("Extension_autoSkipExplicit_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for webnowplaying.js
        /// </summary>
        public static string Extension_webnowplaying_Title {
            get {
                return ResourceManager.GetString("Extension_webnowplaying_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for webnowplaying.js
        /// </summary>
        public static string Extension_webnowplaying_Description {
            get {
                return ResourceManager.GetString("Extension_webnowplaying_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for hidePodcasts.js
        /// </summary>
        public static string Extension_hidePodcasts_Title {
            get {
                return ResourceManager.GetString("Extension_hidePodcasts_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for hidePodcasts.js
        /// </summary>
        public static string Extension_hidePodcasts_Description {
            get {
                return ResourceManager.GetString("Extension_hidePodcasts_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for beautiful-lyrics.mjs
        /// </summary>
        public static string Extension_beautiful_lyrics_Title {
            get {
                return ResourceManager.GetString("Extension_beautiful_lyrics_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for beautiful-lyrics.mjs
        /// </summary>
        public static string Extension_beautiful_lyrics_Description {
            get {
                return ResourceManager.GetString("Extension_beautiful_lyrics_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for playlist-icons.js
        /// </summary>
        public static string Extension_playlist_icons_Title {
            get {
                return ResourceManager.GetString("Extension_playlist_icons_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for playlist-icons.js
        /// </summary>
        public static string Extension_playlist_icons_Description {
            get {
                return ResourceManager.GetString("Extension_playlist_icons_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for volumePercentage.js
        /// </summary>
        public static string Extension_volumePercentage_Title {
            get {
                return ResourceManager.GetString("Extension_volumePercentage_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for volumePercentage.js
        /// </summary>
        public static string Extension_volumePercentage_Description {
            get {
                return ResourceManager.GetString("Extension_volumePercentage_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension title for adblock.js
        /// </summary>
        public static string Extension_adblock_Title {
            get {
                return ResourceManager.GetString("Extension_adblock_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Extension description for adblock.js
        /// </summary>
        public static string Extension_adblock_Description {
            get {
                return ResourceManager.GetString("Extension_adblock_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for CheckUpdates
        /// </summary>
        public static string Maintenance_CheckUpdates_Title {
            get {
                return ResourceManager.GetString("Maintenance_CheckUpdates_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for CheckUpdates
        /// </summary>
        public static string Maintenance_CheckUpdates_Description {
            get {
                return ResourceManager.GetString("Maintenance_CheckUpdates_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for CheckUpdates
        /// </summary>
        public static string Maintenance_CheckUpdates_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_CheckUpdates_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for Reapply
        /// </summary>
        public static string Maintenance_Reapply_Title {
            get {
                return ResourceManager.GetString("Maintenance_Reapply_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for Reapply
        /// </summary>
        public static string Maintenance_Reapply_Description {
            get {
                return ResourceManager.GetString("Maintenance_Reapply_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for Reapply
        /// </summary>
        public static string Maintenance_Reapply_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_Reapply_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for RepairMarketplace
        /// </summary>
        public static string Maintenance_RepairMarketplace_Title {
            get {
                return ResourceManager.GetString("Maintenance_RepairMarketplace_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for RepairMarketplace
        /// </summary>
        public static string Maintenance_RepairMarketplace_Description {
            get {
                return ResourceManager.GetString("Maintenance_RepairMarketplace_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for RepairMarketplace
        /// </summary>
        public static string Maintenance_RepairMarketplace_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_RepairMarketplace_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for OpenMarketplace
        /// </summary>
        public static string Maintenance_OpenMarketplace_Title {
            get {
                return ResourceManager.GetString("Maintenance_OpenMarketplace_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for OpenMarketplace
        /// </summary>
        public static string Maintenance_OpenMarketplace_Description {
            get {
                return ResourceManager.GetString("Maintenance_OpenMarketplace_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for OpenMarketplace
        /// </summary>
        public static string Maintenance_OpenMarketplace_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_OpenMarketplace_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for SafeMode
        /// </summary>
        public static string Maintenance_SafeMode_Title {
            get {
                return ResourceManager.GetString("Maintenance_SafeMode_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for SafeMode
        /// </summary>
        public static string Maintenance_SafeMode_Description {
            get {
                return ResourceManager.GetString("Maintenance_SafeMode_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for SafeMode
        /// </summary>
        public static string Maintenance_SafeMode_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_SafeMode_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for CreateBackup
        /// </summary>
        public static string Maintenance_CreateBackup_Title {
            get {
                return ResourceManager.GetString("Maintenance_CreateBackup_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for CreateBackup
        /// </summary>
        public static string Maintenance_CreateBackup_Description {
            get {
                return ResourceManager.GetString("Maintenance_CreateBackup_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for CreateBackup
        /// </summary>
        public static string Maintenance_CreateBackup_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_CreateBackup_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for RestoreBackup
        /// </summary>
        public static string Maintenance_RestoreBackup_Title {
            get {
                return ResourceManager.GetString("Maintenance_RestoreBackup_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for RestoreBackup
        /// </summary>
        public static string Maintenance_RestoreBackup_Description {
            get {
                return ResourceManager.GetString("Maintenance_RestoreBackup_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for RestoreBackup
        /// </summary>
        public static string Maintenance_RestoreBackup_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_RestoreBackup_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for RestoreVanilla
        /// </summary>
        public static string Maintenance_RestoreVanilla_Title {
            get {
                return ResourceManager.GetString("Maintenance_RestoreVanilla_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for RestoreVanilla
        /// </summary>
        public static string Maintenance_RestoreVanilla_Description {
            get {
                return ResourceManager.GetString("Maintenance_RestoreVanilla_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for RestoreVanilla
        /// </summary>
        public static string Maintenance_RestoreVanilla_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_RestoreVanilla_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for UninstallSpicetify
        /// </summary>
        public static string Maintenance_UninstallSpicetify_Title {
            get {
                return ResourceManager.GetString("Maintenance_UninstallSpicetify_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for UninstallSpicetify
        /// </summary>
        public static string Maintenance_UninstallSpicetify_Description {
            get {
                return ResourceManager.GetString("Maintenance_UninstallSpicetify_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for UninstallSpicetify
        /// </summary>
        public static string Maintenance_UninstallSpicetify_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_UninstallSpicetify_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for FullReset
        /// </summary>
        public static string Maintenance_FullReset_Title {
            get {
                return ResourceManager.GetString("Maintenance_FullReset_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for FullReset
        /// </summary>
        public static string Maintenance_FullReset_Description {
            get {
                return ResourceManager.GetString("Maintenance_FullReset_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for FullReset
        /// </summary>
        public static string Maintenance_FullReset_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_FullReset_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action title for RemoveSelfData
        /// </summary>
        public static string Maintenance_RemoveSelfData_Title {
            get {
                return ResourceManager.GetString("Maintenance_RemoveSelfData_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action description for RemoveSelfData
        /// </summary>
        public static string Maintenance_RemoveSelfData_Description {
            get {
                return ResourceManager.GetString("Maintenance_RemoveSelfData_Description", resourceCulture);
            }
        }
        /// <summary>
        ///   Maintenance action button text for RemoveSelfData
        /// </summary>
        public static string Maintenance_RemoveSelfData_ButtonText {
            get {
                return ResourceManager.GetString("Maintenance_RemoveSelfData_ButtonText", resourceCulture);
            }
        }
        /// <summary>
        ///   Recommended mode highlight 1
        /// </summary>
        public static string RecommendedHighlight_1 {
            get {
                return ResourceManager.GetString("RecommendedHighlight_1", resourceCulture);
            }
        }
        /// <summary>
        ///   Recommended mode highlight 2
        /// </summary>
        public static string RecommendedHighlight_2 {
            get {
                return ResourceManager.GetString("RecommendedHighlight_2", resourceCulture);
            }
        }
        /// <summary>
        ///   Recommended mode highlight 3
        /// </summary>
        public static string RecommendedHighlight_3 {
            get {
                return ResourceManager.GetString("RecommendedHighlight_3", resourceCulture);
            }
        }
        /// <summary>
        ///   Recommended mode highlight 4
        /// </summary>
        public static string RecommendedHighlight_4 {
            get {
                return ResourceManager.GetString("RecommendedHighlight_4", resourceCulture);
            }
        }
    }
}
